spring:
#  data:
#    mongodb:
#        host: localhost
#        port: 27017
#        database: moviemang
#        username: moviemang
#        password: moviemang-pass
  jpa:
    open-in-view: false
    generate-ddl: true
    show-sql: true
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy
    properties:
      format_sql: true
management:
  endpoint:
    health:
      enabled: true
      show-details: always
  endpoints:
    web:
      cors:
        allowed-methods: *
      exposure:
        include: '*'
  health:
    diskspace:
      enabled: true
movie:
  api-key: cbfa45007409cc068286bfeafd12a530
  base-url : https://api.themoviedb.org/3/
  img-url: https://image.tmdb.org/t/p/w500