spring:
  profiles: local
  h2:
    console:
      enabled: true  # H2 ? ??? ?????? ??
      path: /test  # ??? ??
  #  datasource:
  #    url: jdbc:mariadb://localhost:3306/test
  #    driver-class-name: org.mariadb.jdbc.Driver
  #    username: root
  #    password: 1111
  jpa:
    open-in-view: false
    generate-ddl: true
    show-sql: true
    hibernate:
      database-platform: org.hibernate.dialect.MariaDB103Dialect
      ddl-auto: none
    properties:
      format_sql: true
management:
  endpoint:
    health:
      enabled: true
      show-details: always
  endpoints:
    web:
      cors:
        allowed-methods: GET,POST
      exposure:
        include: '*'
  health:
    diskspace:
      enabled: true
