
movie:
  api-key: cbfa45007409cc068286bfeafd12a530
  base-url : https://api.themoviedb.org/3/
  img-base-url: https://image.tmdb.org/t/p/w500

---

spring:
  config:
    activate:
      on-profile: local
  jpa:
    open-in-view: false
    generate-ddl: true
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      format_sql: true
  management:
    endpoint:
      health:
        enabled: true
        show-details: always
    endpoints:
      web:
        cors:
          allowed-methods: '*'
        exposure:
          include: '*'
    health:
      diskspace:
        enabled: true


---

spring:
  config:
    activate:
      on-profile: prod
  jpa:
    open-in-view: false
    generate-ddl: true
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      format_sql: true
  management:
    endpoint:
      health:
        enabled: true
        show-details: always
    endpoints:
      web:
        cors:
          allowed-methods: '*'
        exposure:
          include: '*'
    health:
      diskspace:
        enabled: true





