spring:
  data:
    mongodb:
      host: localhost
      port: 27019
      database: moviemang
      username: root
      password: root-pass
  jpa:
    open-in-view: false
    generate-ddl: true
    show-sql: true
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy
    properties:
      format_sql: true
management:
  endpoint:
    health:
      enabled: true
      show-details: always
  endpoints:
    web:
      cors:
        allowed-methods: *
      exposure:
        include: '*'
  health:
    diskspace:
      enabled: true
