version: "3.7"
services:
  moviemang-mariadb:
    image: mariadb:latest
    container_name: mariadb
    restart: always
    ports:
      - "3306:3306"
    environment:
      - MYSQL_DATABASE=moviemang
      - MYSQL_ROOT_PASSWORD=root-pass
      - MYSQL_USER=moviemang
      - MYSQL_PASSWORD=moviemang-pass
      - TZ=Asia/Seoul
    command: # 명령어 실행
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
      - --lower_case_table_names=1
    volumes:
      - ./maria/data:/var/lib/mysql
  moviemang-mongodb:
    image: mongo:latest
    container_name: mongodb
    restart: always
    ports:
      - 27017:27017
    volumes:
      - ./mongo:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=root-pass
      - MONGO_INITDB_DATABASE=moviemang