spring: 
  mail:
    host: smtp.gmail.com
    port: 465
    username: moviemang2@gmail.com
    password: jzmljjxrbvvqgqyq
    default-encoding: UTF-8
    protocol: smtps
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable : true
